<h2>Logowanie</h2>

<?php echo $this->tag->form('') ?>

<div class="form-group">
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField([
        'email',
        'class' => 'form-control',
    ]) ?>
</div>

<div class="form-group">
    <label for="password">Hasło</label>
    <?php echo $this->tag->passwordField([
        'password',
        'class' => 'form-control',
    ]) ?>
</div>

<p>
    <?php echo $this->tag->submitButton([
        'Zaloguj się',
        'class' => 'btn btn-primary',
    ]) ?>
</p>

</form>
