<h2>Dodaj produkt</h2>

<?php echo $this->tag->form('') ?>

<div class="form-group">
    <label for="name">Nazwa</label>
    <?php echo $this->tag->textField([
        'name',
        'class' => 'form-control',
    ]) ?>
</div>
<div class="form-group">
    <label for="description">Opis</label>
    <?php echo $this->tag->textField([
        'description',
        'class' => 'form-control',
    ]) ?>
</div>
<div class="form-group">
    <label for="price">Cena</label>
    <?php echo $this->tag->textField([
        'price',
        'class' => 'form-control',
    ]) ?>
</div>
<div class="form-group">
    <?php echo $this->tag->submitButton([
        'Dodaj',
        'class' => 'btn btn-primary',
    ]) ?>

</div>
<?php echo $this->tag->endForm() ?>
